### ISSUE TITLE
[Bug]: Editing a room name several times crashes

### ISSUE THREAD

**Issue by miguel-felix1** [xgeekshq/intelli-mate#189]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
 If a user presses the Save button, on a room they own, multiple times, the website will crash

* **What is the expected behavior?**
 Limit the amount of saves, don't allow saving if nothing was changed, backend probably didn't like too many requests sent

**Comment by comoser** [comment]
Solved in main as hotfix
